### ISSUE TITLE
test on a list of onion websites

### ISSUE THREAD

**Issue by x0rzkov** [creekorful/trandoshan#1]
Hi,

Hope you are all well !

Just a quick suggestion, you could bulk/test trandoshan on the list of onion websites available at https://github.com/onionltd/oniontree

I am curious how to bulk add them ? how much will fail because of a captacha challenge.

Thanks in advance for your insights and inputs on that.

Cheers,
X

**Comment by creekorful** [comment]
Hello @x0rzkov !

Since commit https://github.com/creekorful/trandoshan/commit/75fa6724c9b45dca159dfe17f6c3f91a5c3aa670 the API server is exposed by default (on localhost:15005).

One can then use the feeder to push an url to the crawler:

```
feeder --api-uri http://localhost:15005 --url https://www.facebookcorewwwi.onion
```

To bulk add them, you'll only need to run a script that will iterate over your URLs and push them with the feeder.

Cheers!
