### ISSUE TITLE
Error while submiting new URL through the API

### ISSUE THREAD

**Issue by woonhulktin** [creekorful/trandoshan#14]
Hi, I'm quite interested in this crawler but I got an error when I tried to start it. So I just added 
```
feeder:
    image: trandoshan.io/feeder:latest
    command: --log-level debug --api-uri http://localhost:15005 --url http://torlinkbgs6aabns.onion/
```
to the `docker-compose.yml` and executed `./scripts/start.sh`. But the feeder didn't work properly and returned the following message: `feeder_1         | time="2020-08-26T11:43:50Z" level=error msg="Unable to publish URL: Post \"http://localhost:15005/v1/urls\": dial tcp 127.0.0.1:15005: connect: connection refused"`
I did some search online but failed to solve this problem. Could anyone give me some hints? Thank you!

**Comment by creekorful** [comment]
Hello there!

If you are using the feeder directly with docker-compose you must not use `http://localhost:15005` to reach the API but `http://api:8080` instead (since they are in the same virtual network).

Using `http://localhost:15005` is only when you want to reach the API from your host (i.e your computer).
