### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#2]
I tried the new project but can't get past "Kibana server is not ready yet".  I used the packaged build and start scripts.  Are there additional steps or an installation guide somewhere?

Edit: Everything appeared to start OK, here's my output:
Starting deployments_nats_1          ... done
Starting deployments_elasticsearch_1 ... done
Starting deployments_torproxy_1      ... done
Starting deployments_scheduler_1     ... done
Starting deployments_crawler_1       ... done
Starting deployments_kibana_1        ... done
Starting deployments_api_1           ... done
Starting deployments_persister_1     ... done
Attaching to deployments_torproxy_1, deployments_nats_1, deployments_elasticsearch_1, deployments_scheduler_1, deployments_crawler_1, deployments_api_1, deployments_kibana_1, deployments_persister_1
torproxy_1       | WARNING: no logs are available with the 'none' log driver
nats_1           | WARNING: no logs are available with the 'none' log driver
elasticsearch_1  | WARNING: no logs are available with the 'none' log driver
scheduler_1      | time="2020-08-05T21:39:31Z" level=info msg="Starting trandoshan-scheduler v0.0.1"
scheduler_1      | time="2020-08-05T21:39:31Z" level=debug msg="Using NATS server at: nats"
scheduler_1      | time="2020-08-05T21:39:31Z" level=debug msg="Using API server at: http://api:8080"
scheduler_1      | time="2020-08-05T21:39:31Z" level=info msg="Successfully initialized trandoshan-scheduler. Waiting for URLs"
crawler_1        | time="2020-08-05T21:39:32Z" level=info msg="Starting trandoshan-crawler v0.0.1"
crawler_1        | time="2020-08-05T21:39:32Z" level=debug msg="Using NATS server at: nats"
crawler_1        | time="2020-08-05T21:39:32Z" level=debug msg="Using TOR proxy at: torproxy:9050"
crawler_1        | time="2020-08-05T21:39:32Z" level=info msg="Successfully initialized trandoshan-crawler. Waiting for URLs"
api_1            | {"time":"2020-08-05T21:39:33.269084605Z","level":"INFO","prefix":"echo","file":"api.go","line":"73","message":"Starting trandoshan-api v0.0.1"}
api_1            | {"time":"2020-08-05T21:39:33.269182929Z","level":"DEBUG","prefix":"echo","file":"api.go","line":"75","message":"Using elasticsearch server at: http://elasticsearch:9200"}
api_1            | {"time":"2020-08-05T21:39:33.295324468Z","level":"INFO","prefix":"echo","file":"api.go","line":"88","message":"Successfully initialized trandoshan-api. Waiting for requests"}
api_1            | ⇨ http server started on [::]:8080
kibana_1         | WARNING: no logs are available with the 'none' log driver
persister_1      | time="2020-08-05T21:39:34Z" level=info msg="Starting trandoshan-persister v0.0.1"
persister_1      | time="2020-08-05T21:39:34Z" level=debug msg="Using NATS server at: nats"
persister_1      | time="2020-08-05T21:39:34Z" level=debug msg="Using API server at: http://api:8080"
persister_1      | time="2020-08-05T21:39:34Z" level=info msg="Successfully initialized trandoshan-persister. Waiting for resources"
deployments_elasticsearch_1 exited with code 1

**Comment by creekorful** [comment]
Hello!

> deployments_elasticsearch_1 exited with code 1

Looks like the elasticsearch container has been terminated. How much RAM do you have on our machine?

I have faced the same issue one time, and this has been fixed by increasing available memory inside the container:
https://github.com/creekorful/trandoshan/blob/8a32bbe5fac881c7916ec2de44c9b2b0c9b37201/deployments/docker-compose.yml#L18

**Comment by FFrozTT** [comment]
You were right. I was trying on a weak machine with only 1GB.  I upped it to 3GB and it's loading now. I need to spend some time figuring out Kibana but do you have any Quick Start pointers for a PoC?

**Comment by creekorful** [comment]
> You were right. I was trying on a weak machine with only 1GB. I upped it to 3GB and it's loading now. I need to spend some time figuring out Kibana but do you have any Quick Start pointers for a PoC?

Sure.

# Prepare the feeder process

The feeder process is commented in: https://github.com/creekorful/trandoshan/blob/8a32bbe5fac881c7916ec2de44c9b2b0c9b37201/deployments/docker-compose.yml#L34
you'll have to un-commented it, and set an appropriate URL.

# Start the crawler

Just execute the ``/scripts/start.sh`` and wait for all containers to start.
You should see the crawling process in action.

## Note

Sometimes the crawling process may not start, this is because the feeder process is starting before the rest of the dependencies are online. In that case wait for all processes to be online, then execute the following command:

```
docker-compose run feeder
```

this will manually restart the feeder.

# Access the Kibana UI to view results

Just head out to http://localhost:15004

Then you'll need to create an index pattern named 'resources',
then, it will somewhere ask you the time field, choose 'time'.

And you should be good.

**Comment by creekorful** [comment]
If it does work for you, do you mind submitting a PR to update README.md with these details?

**Comment by FFrozTT** [comment]
OK, my GitFu is behind the times but I think I've done that.  

I can see on the discovery tab it has crawled the feeder seed page, and the crawler has found a bunch of links.  The scheduler is having difficulties reading/processing them though:

"Processing URL: http://cyruservvvklto2l.onion/"
scheduler_1      | time="2020-08-06T21:45:27Z" level=error msg="Error while searching URL: %!s(<nil>)"

Kibana is only showing the original seed page ATM.

If I can get this to work, my next task would be accessing the API to dynamically push requests in (I'm thinking via Scumblr or something like that.) However I don't think the API docker is exposed here.  Is there another way I could do that?

**Comment by creekorful** [comment]
> OK, my GitFu is behind the times but I think I've done that.

Thank you! I really appreciate that.

> "Processing URL: http://cyruservvvklto2l.onion/"
> scheduler_1 | time="2020-08-06T21:45:27Z" level=error msg="Error while searching URL: %!s()"

It look likes the scheduler is having bad time trying to reach the API. Is the API process online?
What's the HTTP code returned by the API (it's the line under ``level=error msg="Error while searching URL: %!s()"``)

> Kibana is only showing the original seed page ATM.

That's because the scheduler process fails.

> If I can get this to work, my next task would be accessing the API to dynamically push requests in (I'm thinking via Scumblr > or something like that.) However I don't think the API docker is exposed here. Is there another way I could do that?

Exposing the docker API would be a bad idea, it's a security issue, what if you doesn't want to use Docker anymore?

I don't know if you are comfortable with Go, but I have an implementation idea. I will open an issue and link it here.

**Comment by creekorful** [comment]
Here it is. #4 

Just let me know if you're not comfortable with Go. I'll handle it

**Comment by FFrozTT** [comment]
The api process is online. The initial feed results in dozens of crawler and scheduler messages but only one api message which references the seed. I'm not seeing any api messages resulting from all the processing the scheduler is doing.

The scheduler is also showing all 404 errors which seems a bit odd. It's possible some links are dead but certainly not all of them. I tested several manually and they loaded so I think something is causing the crawler to fail every lookup after the initial feed.

**Comment by creekorful** [comment]
> The api process is online. The initial feed results in dozens of crawler and scheduler messages but only one api message which references the seed. I'm not seeing any api messages resulting from all the processing the scheduler is doing.
> 
> The scheduler is also showing all 404 errors which seems a bit odd. It's possible some links are dead but certainly not all of them. I tested several manually and they loaded so I think something is causing the crawler to fail every lookup after the initial feed.

I'll check what's going on to make sure nothing's broken!

**Comment by creekorful** [comment]
I have confirmed the bug, will work on it. 
Thank you!
